version: "3.3"
services:
  qbittorrent:
    image: vyg1pur0.mirror.aliyuncs.com/linuxserver/qbittorrent
    container_name: ds-qbittorrent
    restart: unless-stopped
    environment:    
      - WEBUI_PORT=${QBITTORRENT_WEB_PORT}
      - UMASK_SET=022
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=Asia/Hong_Kong
    volumes:
      - /etc/localtime:/etc/localtime
      - ./qbittorrent/config:/config
      - ${HARD_DISK_PATH}/downloads:/downloads
    ports:
      - "${QBITTORRENT_WEB_PORT}:${QBITTORRENT_WEB_PORT}"
      #由于PT站把6881列为balcklist所以改端口
      - "${QBITTORRENT_PORT}:${QBITTORRENT_PORT}/tcp"
      - "${QBITTORRENT_PORT}:${QBITTORRENT_PORT}/udp"
  transmission:
    image: vyg1pur0.mirror.aliyuncs.com/linuxserver/transmission:latest
    container_name: ds-transmission
    restart: unless-stopped
    environment:
      - TRANSMISSION_WEB_HOME=/transmission-web-control/
      - USER=${TRANSMISSION_USER}
      - PASS=${TRANSMISSION_PASS}
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=Asia/Hong_Kong
    volumes:
      - /etc/localtime:/etc/localtime
      - ./transmission/config:/config
      - ./transmission/watch:/watch
      - ${HARD_DISK_PATH}/downloads:/downloads
    ports:
      - "${TRANSMISSION_WEB_PORT}:9091"
      - "${TRANSMISSION_PORT}:${TRANSMISSION_PORT}/tcp"
      - "${TRANSMISSION_PORT}:${TRANSMISSION_PORT}/udp"
  aria2:
    image: wahyd4/aria2-ui:arm32
    container_name: ds-aria2
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - ENABLE_AUTH=true
      - ARIA2_USER=${ARIA2_USER}
      - ARIA2_PWD=${ARIA2_PWD}
      - RPC_SECRET=${ARIA2_SECRET}
    volumes:
      - /etc/localtime:/etc/localtime
      - ./aria2/conf:/app/conf
      - ./aria2/filebrowser.db:/app/filebrowser.db
      - ${HARD_DISK_PATH}/downloads:/data
    ports:
      - "${ARIA2_WEB_PORT}:80"  
  bitwarden:
    image: bitwardenrs/server:raspberry
    container_name: ds-bitwarden
    restart: unless-stopped
    environment:
      #由于用nginx proxy所以不需要设置这里绑域名  
      #- DOMAIN=yourdomain.cn
      #- ROCKET_TLS={certs="/acme/yourdomain.cn.pem",key="/acme/yourdomain.cn.key"}
      - SIGNUPS_ALLOWED=false
      - SMTP_EXPLICIT_TLS=${BITWARDEN_SMTP_SSL}      
      - SMTP_HOST=${BITWARDEN_SMTP_HOST}      
      - SMTP_SSL=${BITWARDEN_SMTP_SSL}
      - SMTP_PORT=${BITWARDEN_SMTP_PORT}
      - SMTP_FROM=${BITWARDEN_SMTP_FROM}
      - SMTP_USERNAME=${BITWARDEN_SMTP_USERNAME}
      - SMTP_PASSWORD=${BITWARDEN_SMTP_PASSWORD}
    volumes:
      - /etc/localtime:/etc/localtime
      - ./bitwarden:/data
    ports:
      - "${BITWARDEN_WEB_PORT}:80"
  mysql:
    image: hypriot/rpi-mysql
    container_name: ds-mysql
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime
      - ./mysql/conf/my.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
      - ./mysql/data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
  nextcloud:
    image: nextcloud:fpm
    container_name: ds-nextcloud
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime
      #数据存储在移动硬盘上
      - ${HARD_DISK_PATH}/wwwroot:/var/www/html    
      - ${HARD_DISK_PATH}/nextcloud/data:/var/www/html/data
  nginx:
    image: nginx:1.17.6-alpine
    restart: unless-stopped
    container_name: ds-nginx
    working_dir: /var/www/html
    volumes:
      - /etc/localtime:/etc/localtime
      - ${HARD_DISK_PATH}/wwwroot:/var/www/html
      - ./nginx:/etc/nginx/conf.d
      - ./acme:/acme
    depends_on:
      - nextcloud
      - mysql
    ports:
      #由于omv占用了80所以改其他
      - "${NGINX_HTTP_PORT}:${NGINX_HTTP_PORT}"
      - "${NGINX_HTTPS_PORT}:${NGINX_HTTPS_PORT}"
  jellyfin:
    image: vyg1pur0.mirror.aliyuncs.com/linuxserver/jellyfin:arm32v7-latest
    container_name: ds-jellyfin
    restart: unless-stopped
    #network_mode: host
    environment:
      # 先写定pi 用户和video组
      - PUID=1000
      - PGID=44
      - TZ=Asia/Hong_Kong
      - UMASK_SET=022 
    volumes:
      # 转码时会在/config/data/transcodes目录
      # 估计TF卡读写原因影响性能，推荐映到移动硬盘
      - ${HARD_DISK_PATH}/jellyfin/config:/config
      - /opt/vc/lib:/opt/vc/lib
      - ${HARD_DISK_PATH}/downloads/tv:/data/tvshows
      - ${HARD_DISK_PATH}/downloads/movice:/data/movies
    ports:
      - 8096:8096
      - 8920:8920 
    devices:
      #开启open OMX硬解
      - /dev/vc-mem:/dev/vc-mem
      - /dev/vchiq:/dev/vchiq
  frp: 
    image: vyg1pur0.mirror.aliyuncs.com/snowdreamtech/frpc:latest   
    restart: unless-stopped
    container_name: ds-frp
    command: daemon
    network_mode: host
    volumes:
      - /etc/localtime:/etc/localtime
      - ./frp/frpc.ini:/etc/frp/frpc.ini
      - ./acme:/acme
  frp: 
    image: vyg1pur0.mirror.aliyuncs.com/snowdreamtech/frpc:latest   
    restart: unless-stopped
    container_name: ds-frp
    command: daemon
    network_mode: host
    volumes:
      - /etc/localtime:/etc/localtime
      - ./frp/frpc.ini:/etc/frp/frpc.ini
      - ./acme:/acme
  homeassistant:
    container_name: home-assistant
    image: vyg1pur0.mirror.aliyuncs.com/homeassistant/raspberrypi4-homeassistant:latest
    privileged: true
    restart: always
    network_mode: host
    ports:
      - ${HOME_ASSISTANT_HTTP_PORT}:8123
    devices:
      - /dev/bus/usb:/dev/bus/usb
      - /dev/snd:/dev/snd
    environment:
      - TZ=Asia/Hong_Kong
    volumes:
      - /etc/localtime:/etc/localtime
      - ${HARD_DISK_PATH}/homeassistant/confg:/config

